### ISSUE TITLE
Remix: TypeError: Value of "this" must be of type URLSearchParams

### ISSUE THREAD

**Issue by aurorascharff** [kentcdodds/the-webs-next-transformation#12]
Running node dev 6 or 7 (the Remix apps) returns error.
All examples working great so far until these ones. Awesome stuff! :)

Using node 20, I see that the Readme says 14 || 16 || 18.
https://github.com/remix-run/remix/issues/6118
Would be nice to be able to run this in node 20! Sorry if this is a known issue and you don't plan on upgrading the Remix apps. But, I thought since this is an older project, it would be worth letting you know.

```
TypeError: Value of "this" must be of type URLSearchParams
    at Proxy.set (node:internal/url:579:13)
    at Proxy.<anonymous> (C:\Users\aurwalbe\source\repos\the-webs-next-transition\node_modules\@remix-run\web-fetch\src\headers.js:124:44)
    at createRemixHeaders (C:\Users\aurwalbe\source\repos\the-webs-next-transition\node_modules\@remix-run\express\dist\server.js:58:17)
    at createRemixRequest (C:\Users\aurwalbe\source\repos\the-webs-next-transition\node_modules\@remix-run\express\dist\server.js:73:14)
    at C:\Users\aurwalbe\source\repos\the-webs-next-transition\node_modules\@remix-run\express\dist\server.js:37:21
    at C:\Users\aurwalbe\source\repos\the-webs-next-transition\node_modules\@remix-run\serve\dist\index.js:48:7
    at Layer.handle [as handle_request] (C:\Users\aurwalbe\source\repos\the-webs-next-transition\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\aurwalbe\source\repos\the-webs-next-transition\node_modules\express\lib\router\route.js:144:13)
    at next (C:\Users\aurwalbe\source\repos\the-webs-next-transition\node_modules\express\lib\router\route.js:140:7)
    at next (C:\Users\aurwalbe\source\repos\the-webs-next-transition\node_modules\express\lib\router\route.js:140:7)
    at next (C:\Users\aurwalbe\source\repos\the-webs-next-transition\node_modules\express\lib\router\route.js:140:7)
    at next (C:\Users\aurwalbe\source\repos\the-webs-next-transition\node_modules\express\lib\router\route.js:140:7)
    at next (C:\Users\aurwalbe\source\repos\the-webs-next-transition\node_modules\express\lib\router\route.js:140:7)
    at next (C:\Users\aurwalbe\source\repos\the-webs-next-transition\node_modules\express\lib\router\route.js:140:7)
    at Route.dispatch (C:\Users\aurwalbe\source\repos\the-webs-next-transition\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\Users\aurwalbe\source\repos\the-webs-next-transition\node_modules\express\lib\router\layer.js:95:5)
```

**Comment by kentcdodds** [comment]
Thanks for letting me know. I'm afraid I don't have the bandwidth to update this repo at the moment. Hopefully looking through the code is enough to get an idea of how the web world has transitioned over time though.

**Comment by aurorascharff** [comment]
Understandable! And yes, it's already good to look at the code, thanks! :)

**Comment by toptal-dave** [comment]
@aurorascharff I just ran up against this when mocking Supabase for a test.  Did you figure out a work around?

**Comment by aurorascharff** [comment]
@toptal-dave I didn't, maybe you can try migrating!
